# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 06:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=250)),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('likes', models.ManyToManyField(related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('general_requirements', models.CharField(max_length=100)),
                ('repeatable', models.BooleanField()),
                ('grading', models.CharField(max_length=40)),
                ('min_units', models.IntegerField()),
                ('max_units', models.IntegerField()),
                ('average_rating', models.FloatField(blank=True, default=None, null=True)),
                ('grade_distribution', jsonfield.fields.JSONField(default=None)),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseCode',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('alt_code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='main.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('term', models.CharField(max_length=15)),
                ('section_number', models.IntegerField()),
                ('num_enrolled', models.IntegerField()),
                ('max_enrolled', models.IntegerField()),
                ('num_waitlist', models.IntegerField()),
                ('max_waitlist', models.IntegerField()),
                ('enroll_status', models.CharField(max_length=32)),
                ('start_date', models.CharField(max_length=31)),
                ('end_date', models.CharField(max_length=30)),
                ('start_time', models.CharField(max_length=29)),
                ('end_time', models.CharField(max_length=28)),
                ('days', models.CharField(max_length=100)),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.IntegerField(choices=[(1, "Bachelor's"), (2, 'Minor'), (3, 'Coterminal')])),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description_html', models.TextField(default='')),
                ('is_updated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('sunet', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('bio', models.TextField(default='')),
                ('is_updated', models.BooleanField(default=False)),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degrees', models.ManyToManyField(related_name='plans', to='main.Degree')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('term', models.CharField(choices=[('Fall', 'Fall'), ('Winter', 'Winter'), ('Spring', 'Spring')], max_length=6)),
                ('courses', models.ManyToManyField(related_name='plan_quarters', to='main.Course')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='main.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_units', models.IntegerField()),
                ('num_classes', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='main.Department')),
                ('eligible_classes', models.ManyToManyField(related_name='requirements', to='main.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')])),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F'), ('CR', 'Credit'), ('NC', 'No credit')], max_length=2, null=True)),
                ('text', models.TextField()),
                ('is_crawled', models.BooleanField(default=False)),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.Course')),
                ('helpful_votes', models.ManyToManyField(related_name='liked_reviews', to=settings.AUTH_USER_MODEL)),
                ('unhelpful_votes', models.ManyToManyField(related_name='_review_unhelpful_votes_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description_html', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunet', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='main.School'),
        ),
        migrations.AddField(
            model_name='degree',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='main.Department'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.Instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='main.Department'),
        ),
    ]
