# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='year',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='term',
            field=models.CharField(max_length=15),
        ),
    ]
