# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 05:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='likes',
            new_name='upvotes',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='helpful_votes',
            new_name='upvotes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='unhelpful_votes',
        ),
        migrations.AddField(
            model_name='comment',
            name='downvotes',
            field=models.ManyToManyField(related_name='_comment_downvotes_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='downvotes',
            field=models.ManyToManyField(related_name='_review_downvotes_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
