# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160813_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='id',
        ),
    ]
