# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-27 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160822_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='is_updated',
        ),
    ]
