# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_department_is_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='median_grade',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='average_rating',
            field=models.IntegerField(default=0),
        ),
    ]
