# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160814_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='average_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='grade_distribution',
            field=jsonfield.fields.JSONField(default=None),
        ),
    ]
