# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_general_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='instructor',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
