# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160804_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='reply_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
