# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160906_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='average_rating',
        ),
    ]
