# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160817_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.IntegerField(choices=[(1, "Bachelor's"), (2, 'Minor'), (3, 'Coterminal')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='main.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degrees', models.ManyToManyField(related_name='plans', to='main.Degree')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='main.Student')),
            ],
        ),
        migrations.CreateModel(
            name='PlanQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('term', models.IntegerField(choices=[(1, 'Fall'), (2, 'Winter'), (3, 'Spring')], max_length=6)),
                ('courses', models.ManyToManyField(related_name='plan_quarters', to='main.Course')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='main.Plan')),
            ],
        ),
    ]
