# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160906_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='median_grade',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
