# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160807_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
