# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160805_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_crawled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.Student'),
        ),
    ]
