# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_course_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='average_rating',
            field=models.IntegerField(default=0),
        ),
    ]
