# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160808_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
