# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_degree_plan_planquarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planquarter',
            name='term',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Winter', 'Winter'), ('Spring', 'Spring')], max_length=6),
        ),
    ]
