# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160805_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
