# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160907_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='last_crawled',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planyear',
            name='autumn',
            field=models.ManyToManyField(blank=True, related_name='plans_autumn', to='main.Course'),
        ),
        migrations.AlterField(
            model_name='planyear',
            name='spring',
            field=models.ManyToManyField(blank=True, related_name='plans_spring', to='main.Course'),
        ),
        migrations.AlterField(
            model_name='planyear',
            name='summer',
            field=models.ManyToManyField(blank=True, related_name='plans_summer', to='main.Course'),
        ),
        migrations.AlterField(
            model_name='planyear',
            name='winter',
            field=models.ManyToManyField(blank=True, related_name='plans_winter', to='main.Course'),
        ),
    ]
