# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160805_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecode',
            name='alt_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
