# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160808_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='end_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='end_time',
            field=models.CharField(max_length=28),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='enroll_status',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='start_date',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='start_time',
            field=models.CharField(max_length=29),
        ),
    ]
