# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_instructor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
