# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-09 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160908_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='planyear',
            name='autumn_sections',
            field=models.ManyToManyField(blank=True, related_name='plans_autumn', to='main.CourseSection'),
        ),
        migrations.AddField(
            model_name='planyear',
            name='spring_sections',
            field=models.ManyToManyField(blank=True, related_name='plans_spring', to='main.CourseSection'),
        ),
        migrations.AddField(
            model_name='planyear',
            name='summer_sections',
            field=models.ManyToManyField(blank=True, related_name='plans_summer', to='main.CourseSection'),
        ),
        migrations.AddField(
            model_name='planyear',
            name='winter_sections',
            field=models.ManyToManyField(blank=True, related_name='plans_winter', to='main.CourseSection'),
        ),
    ]
