# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-09 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20160909_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
