# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-10 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_school_description_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='last_crawled',
        ),
    ]
