# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_review_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='last_crawled',
            field=models.IntegerField(default=0),
        ),
    ]
