# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_department_last_crawled'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='component',
            field=models.CharField(default='', max_length=4),
        ),
    ]
