# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-09 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_coursesection_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(related_name='useful_for', to='main.CourseCode'),
        ),
    ]
