# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-16 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='planyear',
            name='courses',
            field=models.TextField(default='{}'),
        ),
    ]
