# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-18 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_planyear_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='instructors',
            field=models.ManyToManyField(related_name='sections_new', to='main.Instructor'),
        ),
    ]
