# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-18 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_coursesection_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='location',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
